'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const INITIAL_HTML='<h1>Mi espacio web</h1>\n\n<p>¡Hola! Esta es mi primera página.</p>\n\n<h2>Mis intereses</h2>\n\n<ul>\n    <li>Música</li>\n    <li>Videojuegos</li>\n    <li>Deportes</li>\n</ul>\n\n<p>Estoy aprendiendo a crear páginas con HTML y CSS.</p>',INITIAL_CSS='body {\n    font-family: Arial, sans-serif;\n    background-color: white;\n}\n\nh1 {\n    color: blue;\n}\n\nh2 {\n    font-size: 24px;\n}';
const old=LMS.read(),num=(n,max)=>Number.isInteger(n)&&n>=0&&n<=max?n:0,str=(v,max)=>typeof v==='string'?v.slice(0,max):'';
const state={version:4,stage:num(old.stage,3),reached:num(old.reached,3),guided:num(old.guided,2),guidedUnlocked:Math.max(num(old.guidedUnlocked,2),num(old.guided,2)),guidedDone:Array.from({length:3},(_,i)=>!!old.guidedDone?.[i]),situation:num(old.situation,3),situationUnlocked:Math.max(num(old.situationUnlocked,3),num(old.situation,3)),html:typeof old.html==='string'?str(old.html,12000):INITIAL_HTML,css:typeof old.css==='string'?str(old.css,8000):INITIAL_CSS,answers:Array.from({length:5},(_,i)=>({choices:Array.isArray(old.answers?.[i]?.choices)?old.answers[i].choices.filter(x=>['HTML','CSS','content','presentation'].includes(x)).slice(-12):[],observed:!!old.answers?.[i]?.observed})),htmlChange:str(old.htmlChange,200),cssChange:str(old.cssChange,200),intention:str(old.intention,240),modified:str(old.modified,240),where:['HTML','CSS'].includes(old.where)?old.where:'',result:str(old.result,300),transferChoices:Array.isArray(old.transferChoices)?old.transferChoices.filter(x=>['HTML','CSS'].includes(x)).slice(-12):[],reason:str(old.reason,300),transferReason:str(old.transferReason,300),images:old.images&&typeof old.images==='object'?Object.fromEntries(Object.entries(old.images).filter(([k,v])=>/^imagen-\d+\.(png|jpg|webp|gif)$/.test(k)&&typeof v==='string'&&/^data:image\/(png|jpeg|webp|gif);base64,/.test(v)&&v.length<1400000)): {},completed:!!old.completed};
let saveTimer,previewTimer,renderTimer,showCompletion=state.completed;
const titles=['1. Explorá y observá','2. ¿HTML o CSS?','3. Personalizá tu propia página','4. Explicá tu decisión'];
const intros=['Realizá los cambios de a uno. Después de cada modificación, observá qué sucede en la página.','Antes de modificar la página, decidí dónde tendrías que intervenir. Después comprobá tu decisión realizando el cambio.','Transformá la página para que represente tus elecciones.','Elegí uno de los cambios que realizaste en tu página y explicá por qué decidiste hacerlo de esa manera.'];
const situations=[
 ['Querés cambiar el texto del párrafo.','HTML','Buscá el texto entre <p> y </p> y reemplazalo por un texto que elijas.',''],
 ['Querés cambiar el color del título sin modificar lo que dice.','CSS','Localizá color: dentro de h1 y elegí otro color.','Podés probar blue, red, green, purple u orange.'],
 ['Querés agregar un nuevo interés a la lista.','HTML','Agregá un nuevo elemento <li>...</li> dentro de la lista.','<code>&lt;li&gt;Mi nuevo interés&lt;/li&gt;</code>'],
 ['Querés cambiar el tamaño del subtítulo “Mis intereses”.','CSS','Agregá una propiedad font-size al estilo de h2.','Por ejemplo: <code>font-size: 32px;</code><br>Escribila dentro de las llaves <code>{ }</code> del elemento que querés modificar. Podés probar diferentes tamaños.']];

function snapshot(){const data={...state,images:{...state.images}};data.imagesOmitted=Array.from(state.html.matchAll(/src\s*=\s*["'](imagen-\d+\.(?:png|jpg|webp|gif))["']/gi)).some(m=>!data.images[m[1]]);while(JSON.stringify(data).length>58000&&Object.keys(data.images).length){delete data.images[Object.keys(data.images).at(-1)];data.imagesOmitted=true}return data}
function persist(){clearTimeout(saveTimer);const data=snapshot();const ok=LMS.save(data);$('connection').textContent=LMS.readOnly?'Modo de revisión · cambios sin guardar':ok?(LMS.active?(LMS.reduced?'Avance guardado · código no guardado; descargá tu proyecto':'Código y avance guardados en CREA/LMS'):'Modo local · guardado en este navegador'):'No se pudo guardar · reintentá o descargá tu proyecto';if(ok&&data.imagesOmitted&&!LMS.readOnly)$('connection').textContent+=' · alguna imagen no se guardó; descargá el proyecto';$('connection').title=LMS.lastError;return ok}
function schedule(){clearTimeout(saveTimer);$('connection').textContent='Cambios pendientes de guardar…';saveTimer=setTimeout(persist,700)}
function previewDocument(exporting=false){const doc=new DOMParser().parseFromString(state.html,'text/html');doc.querySelectorAll('script,iframe,object,embed,base,meta,link,form').forEach(x=>x.remove());doc.querySelectorAll('*').forEach(el=>{const source=el.tagName==='IMG'?el.getAttribute('src'):null;for(const a of [...el.attributes])if(/^on/i.test(a.name)||['href','src','srcset','action','formaction','autofocus'].includes(a.name.toLowerCase()))el.removeAttribute(a.name);if(source&&state.images[source])el.setAttribute('src',exporting?source:state.images[source]);else if(source&&el.tagName==='IMG'){el.setAttribute('alt',(el.getAttribute('alt')||'Imagen')+' (volvé a cargar la imagen)')}});const csp=doc.createElement('meta');csp.httpEquiv='Content-Security-Policy';csp.content="default-src 'none'; script-src 'none'; style-src 'unsafe-inline'; img-src data:; font-src 'none'; connect-src 'none'; form-action 'none'; base-uri 'none'";doc.head.prepend(csp);const base=doc.createElement('style');base.textContent='img { max-width: 100%; height: auto; }';doc.head.append(base);const style=doc.createElement('style');style.textContent=state.stage===0&&state.guided<2?'':state.css;doc.head.append(style);return '<!doctype html>'+doc.documentElement.outerHTML}
function editorLayout(){const htmlOnly=state.stage===0&&state.guided<2;$('cssEditor').hidden=htmlOnly;$('workspace').classList.toggle('html-only',htmlOnly)}

function render(){clearTimeout(previewTimer);clearTimeout(renderTimer);$('renderStatus').textContent='Actualizando…';if(showCompletion)return;const code=previewDocument();$(state.stage===3?'finalOutput':'output').srcdoc=code;renderTimer=setTimeout(()=>{$('renderStatus').textContent='La vista demora en cargar. Hacé otra modificación para actualizarla.'},5000)}
for(const id of ['output','finalOutput'])$(id).addEventListener('load',()=>{clearTimeout(renderTimer);$('renderStatus').textContent='Vista actualizada · observá qué cambió'});
function feedback(answer,index,expected){if(!answer)return '';if(answer===expected)return index===0?'Exacto. El contenido del título se mantiene; lo que modificaste fue su presentación mediante CSS.':expected==='HTML'?'Correcto. Querés modificar el contenido o la estructura de la página, por eso intervenís en HTML.':'Correcto. Querés modificar cómo se presenta un elemento, por eso intervenís en CSS.';return index===0?'¿Cambió lo que dice el título o cambió la forma en que se presenta?':'¿Querés cambiar qué contiene la página o cómo se presenta?'}
function choices(index,expected){const a=state.answers[index],last=a.choices.at(-1),options=index===0?[['content','El contenido.'],['presentation','La presentación.']]:[['HTML','HTML'],['CSS','CSS']];return `<div class="row" role="group" aria-label="${index===0?'¿Qué cambió principalmente?':'¿Dónde realizarías el cambio?'}">${options.map(([v,t])=>`<button class="secondary" data-answer="${v}" aria-pressed="${last===v}">${t}</button>`).join('')}</div><p class="feedback" id="feedback" role="status" ${last?'':'hidden'}>${esc(feedback(last,index,expected))}</p>`}
function innerNav(kind,count,current,unlocked){return `<div class="inner-nav" role="group" aria-label="${kind==='guided'?'Cambios de la etapa 1':'Situaciones de la etapa 2'}">${Array.from({length:count},(_,i)=>`<button class="secondary" data-${kind}="${i}" ${i>unlocked?'disabled':''} ${i===current?'aria-current="step"':''}>${kind==='guided'?'Cambio ':''}${['A','B','C','D'][i]}${i>unlocked?'<span class="sr-only"> · aún no disponible</span>':''}</button>`).join('')}</div>`}
function task(){editorLayout();render();let index=null,expected=null;const box=$('task');if(state.stage===0){const g=state.guided;box.innerHTML=innerNav('guided',3,g,state.guidedUnlocked)+`<div class="tasktop"><span class="badge">CAMBIO ${['A','B','C'][g]}</span><span class="muted small">Modificá y observá</span></div>`+(g===0?'<h2>Un título propio</h2><p>Buscá en el código HTML el título de tu página (al inicio dice “Mi espacio web”) y reemplazalo por un título que vos elijas.</p><p>Observá qué ocurrió en la página.</p>':g===1?'<h2>Uno de tus intereses</h2><p>Elegí uno de los elementos de la lista y reemplazalo por uno de tus propios intereses.</p><p>Observá nuevamente la página.</p>':'<h2>Anticipá y observá</h2><p>Antes de modificar: localizá en CSS <code>color: blue</code>. ¿Qué pensás que va a cambiar si reemplazás <code>blue</code> por otro color?</p><p>Podés probar <code>red</code>, <code>green</code>, <code>purple</code> u <code>orange</code>. Realizá el cambio y observá el resultado.</p><h2>¿Qué cambió principalmente?</h2>'+choices(0,'presentation'));if(g===2){index=0;expected='presentation'}
box.innerHTML+=state.guidedDone[g]?'<p class="badge">Cambio observado · podés seguir experimentando.</p>':`<button id="guidedNext">${g<2?'Ya modifiqué y observé →':'Ya observé este cambio'}</button>`;
}else if(state.stage===1){index=state.situation+1;expected=situations[state.situation][1];const s=situations[state.situation],a=state.answers[index],correct=a.choices.at(-1)===expected;
box.innerHTML=innerNav('situation',4,state.situation,state.situationUnlocked)+`<span class="badge">SITUACIÓN ${['A','B','C','D'][state.situation]} · ${state.situation+1} de 4</span><h2>${s[0]}</h2><p>¿Dónde realizarías el cambio?</p>${choices(index,expected)}${correct?`<p><strong>Ahora comprobalo en el editor.</strong> ${esc(s[2])}</p>${s[3]?`<p class="syntax-help">${s[3]}</p>`:''}${a.observed?'<p class="badge">Modificación y observación registradas.</p>':'<button id="observed" class="secondary">Ya realicé el cambio y observé</button>'}`:'<p class="muted small">Elegí HTML o CSS. Podés revisar tu respuesta.</p>'}`;
if(a.observed&&state.situation<3)box.innerHTML+='<div class="toolbar"><button id="nextSituation">Siguiente situación →</button></div>';
}else if(state.stage===2){box.innerHTML='<p><strong>Realizá como mínimo:</strong></p><div class="hints"><h2>2 cambios utilizando HTML</h2><h2>2 cambios utilizando CSS</h2></div><p>No es necesario que todas las páginas queden iguales. Elegí qué querés modificar, probá diferentes posibilidades y observá los resultados.</p>'}else box.hidden=true;
if($('guidedNext'))$('guidedNext').onclick=()=>{state.guidedDone[state.guided]=true;if(state.guided<2){state.guidedUnlocked=Math.max(state.guidedUnlocked,state.guided+1);state.guided++}task();persist();focusInternal('guided',state.guided)};
for(const kind of ['guided','situation'])document.querySelectorAll(`[data-${kind}]`).forEach(b=>b.onclick=()=>{const n=+b.dataset[kind];if(n>state[kind+'Unlocked'])return;state[kind]=n;task();persist();focusInternal(kind,n)});
if(index!==null)document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{state.answers[index].choices.push(b.dataset.answer);state.answers[index].choices=state.answers[index].choices.slice(-12);task();persist();document.querySelector(`[data-answer="${b.dataset.answer}"]`)?.focus()});
if($('observed'))$('observed').onclick=()=>{state.answers[index].observed=true;state.situationUnlocked=Math.max(state.situationUnlocked,Math.min(3,state.situation+1));task();persist();document.querySelector(`[data-situation="${state.situation}"]`)?.focus()};
if($('nextSituation'))$('nextSituation').onclick=()=>{state.situation++;task();persist();focusInternal('situation',state.situation)}}
function focusInternal(kind,n){document.querySelector(`[data-${kind}="${n}"]`)?.focus()}
function transferFeedback(){const choice=state.transferChoices.at(-1);$('transferJustification').hidden=choice!=='CSS';$('transferFeedback').hidden=!choice;$('transferFeedback').textContent=choice==='CSS'?'Exacto. Si querés modificar la presentación sin cambiar el contenido, trabajarías principalmente con CSS.':choice?'Si el contenido permanece igual y solamente cambia cómo se presenta, ¿qué lenguaje se ocupa principalmente de la presentación?':''}

function show(stage,focus=true){state.stage=stage;state.reached=Math.max(stage,state.reached);$('title').textContent=titles[stage];$('intro').textContent=intros[stage];$('progress').textContent=`ETAPA ${stage+1} DE 4 · EXPERIMENTÁ CON UNA PÁGINA WEB`;document.querySelectorAll('[data-stage]').forEach(b=>{if(+b.dataset.stage===stage)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});for(const id of ['task','work','personal','changes','explain','finalPreview','completed','tools'])$(id).hidden=true;$('completed').hidden=!showCompletion;const visible=showCompletion?[]:stage===2?['task','personal','work','tools','changes']:stage===3?['finalPreview','explain']:['task','work'];visible.forEach(id=>$(id).hidden=false);$('intro').hidden=showCompletion;$('back').disabled=stage===0;$('next').hidden=showCompletion;$('back').hidden=showCompletion||stage===0;$('next').textContent=stage===3?'Completar actividad':'Continuar →';if(!showCompletion)task();if(focus)$('title').focus();persist()}
for(const id of ['htmlCode','cssCode']){$(id).value=state[id==='htmlCode'?'html':'css'];$(id).addEventListener('input',()=>{state[id==='htmlCode'?'html':'css']=$(id).value;schedule();clearTimeout(previewTimer);previewTimer=setTimeout(render,280)})}
for(const id of ['htmlChange','cssChange','intention','modified','result','reason','transferReason']){$(id).value=state[id];$(id).addEventListener('input',()=>{state[id]=$(id).value;schedule()})}
document.querySelectorAll('[name=where]').forEach(r=>{r.checked=r.value===state.where;r.onchange=()=>{state.where=r.value;schedule()}});
document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{showCompletion=false;show(+b.dataset.stage)});
function validateDecision(){const fields=[['intention','qué querías lograr con ese cambio'],['where','dónde realizaste ese cambio (HTML o CSS)'],['modified','qué modificaste en el código'],['result','qué efecto produjo ese cambio'],['reason','por qué correspondía utilizar HTML o CSS'],['transfer','tu elección en la situación nueva'],['transferReason','por qué elegirías CSS en la situación nueva']];
const missing=fields.filter(([key])=>key==='where'?!state.where:key==='transfer'?state.transferChoices.at(-1)!=='CSS':!state[key].trim());
for(const [key]of fields){const nodes=['where','transfer'].includes(key)?document.querySelectorAll(`[name="${key}"]`):[$(key)];nodes.forEach(el=>{el.removeAttribute('aria-invalid');if(el.id!=='transferReason')el.removeAttribute('aria-describedby')})}
if(!missing.length){$('finishNotice').textContent='';return true}
const names=missing.map(([key,label])=>key==='transfer'&&state.transferChoices.length?'revisar la situación nueva con la pregunta orientadora':label);$('finishNotice').textContent='Falta completar: '+names.join('; ')+'. Tus respuestas se conservan.';
for(const [key]of missing){const nodes=['where','transfer'].includes(key)?document.querySelectorAll(`[name="${key}"]`):[$(key)];nodes.forEach(el=>{el.setAttribute('aria-invalid','true');el.setAttribute('aria-describedby',key==='transferReason'?'transferReasonHelp finishNotice':'finishNotice')})}
let first=missing[0][0];if(first==='transferReason'&&$('transferJustification').hidden)first='transfer';(['where','transfer'].includes(first)?document.querySelector(`[name="${first}"]`):$(first)).focus();return false}
$('back').onclick=()=>show(Math.max(0,state.stage-1));$('next').onclick=()=>{if(state.stage<3){show(state.stage+1);return}if(!validateDecision())return;state.completed=true;showCompletion=true;show(3);$('completed').setAttribute('tabindex','-1');$('completed').focus()};
$('review').onclick=()=>{showCompletion=false;show(3)};$('save').onclick=persist;$('decisionHint').onclick=()=>{$('decisionHintText').hidden=!$('decisionHintText').hidden;$('decisionHint').setAttribute('aria-expanded',!$('decisionHintText').hidden)};
$('reset').onclick=()=>$('resetDialog').showModal();$('cancelReset').onclick=()=>$('resetDialog').close();$('confirmReset').onclick=()=>{state.html=INITIAL_HTML;state.css=INITIAL_CSS;state.images={};$('htmlCode').value=state.html;$('cssCode').value=state.css;$('resetDialog').close();render();persist()};
$('download').onclick=()=>{const doc=new DOMParser().parseFromString(previewDocument(true),'text/html');const styles=doc.head.querySelectorAll('style');styles[styles.length-1].remove();const link=doc.createElement('link');link.rel='stylesheet';link.href='styles.css';doc.head.querySelector('meta[http-equiv]').remove();doc.head.append(link);const files={'index.html':'<!doctype html>'+doc.documentElement.outerHTML,'styles.css':state.css,'mis-cambios.txt':`HTML: ${state.htmlChange}\nCSS: ${state.cssChange}\nIntención: ${state.intention}\nLenguaje: ${state.where}\nCódigo: ${state.modified}\nEfecto: ${state.result}\nPor qué: ${state.reason}\nTransferencia: ${state.transferChoices.at(-1)||''}\nJustificación de la situación nueva: ${state.transferReason}`};for(const [name,data]of Object.entries(state.images))files[name]=Uint8Array.from(atob(data.split(',')[1]),c=>c.charCodeAt(0));const url=URL.createObjectURL(projectZip(files)),a=document.createElement('a');a.href=url;a.download='mi-pagina-web.zip';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000)};
document.querySelectorAll('[name=transfer]').forEach(r=>{r.checked=r.value===state.transferChoices.at(-1);r.onchange=()=>{state.transferChoices.push(r.value);state.transferChoices=state.transferChoices.slice(-12);transferFeedback();schedule()}});transferFeedback();
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')persist()});window.addEventListener('pagehide',e=>{if(e.persisted)persist();else LMS.finish(snapshot())});window.addEventListener('beforeunload',persist);show(state.stage,false);if(old.codeOmitted)$('connection').textContent='Avance recuperado · el LMS no conservó el código; se cargó el ejemplo inicial';

if(old.imagesOmitted)$('connection').textContent+=' · algunas imágenes no se recuperaron; volvé a cargarlas';
