'use strict';
// Ayudas opcionales: todas muestran e incorporan código editable.
function openTool(id){document.querySelectorAll('.tool-panel').forEach(p=>p.hidden=p.id!==id);document.querySelectorAll('[data-tool]').forEach(b=>b.setAttribute('aria-expanded',b.dataset.tool===id))}
document.querySelectorAll('[data-tool]').forEach(b=>{b.setAttribute('aria-controls',b.dataset.tool);b.onclick=()=>{const id=b.dataset.tool;if(!$(id).hidden){$(id).hidden=true;b.setAttribute('aria-expanded','false')}else openTool(id)}});
function updateCode(type,text,status){const el=$(type==='html'?'htmlCode':'cssCode');if(text.length>el.maxLength){$(status).textContent='El editor está lleno. Quitá algo de código antes de insertar.';return false}state[type]=text;el.value=text;render();persist();$(status).textContent=`Código ${type.toUpperCase()} actualizado · observá la página y podés seguir editándolo.`;return true}
function rule(selector,declarations){return selector+' {\n    '+declarations.join('\n    ')+'\n}'}
function applyRule(selector,declarations,status,tag){const marker='/* Herramienta: '+tag+' · '+selector+' */',end='/* Fin herramienta */',block=marker+'\n'+rule(selector,declarations)+'\n'+end;let css=state.css;const a=css.indexOf(marker),b=a<0?-1:css.indexOf(end,a);css=a>=0&&b>=0?css.slice(0,a)+block+css.slice(b+end.length):css+'\n\n'+block;return updateCode('css',css,status)}
function htmlInsertion(fragment,kind=''){const html=state.html;if(kind==='li'){const close=/<\/(ul|ol)\s*>/i;if(close.test(html))return html.replace(close,m=>'    '+fragment+'\n'+m);fragment='<ul>\n    '+fragment+'\n</ul>'}const body=/<\/body\s*>/i;return body.test(html)?html.replace(body,fragment+'\n</body>'):html+'\n\n'+fragment}
let hue=233,sat=53,bright=77,opacity=100;
function rgb(){const c=bright/100*sat/100,x=c*(1-Math.abs((hue/60)%2-1)),m=bright/100-c;const v=hue<60?[c,x,0]:hue<120?[x,c,0]:hue<180?[0,c,x]:hue<240?[0,x,c]:hue<300?[x,0,c]:[c,0,x];return v.map(n=>Math.round((n+m)*255))}
function hex(){return '#'+rgb().map(n=>n.toString(16).padStart(2,'0')).join('').toUpperCase()+(opacity<100?Math.round(opacity*255/100).toString(16).padStart(2,'0').toUpperCase():'')}
function refreshColor(){const value=hex();$('nativeColor').value=value.slice(0,7);$('hexColor').value=value;$('hexColor').removeAttribute('aria-invalid');for(const [id,v,label]of [['hue',hue,'°'],['saturation',sat,'%'],['brightness',bright,'%'],['alpha',opacity,'%']]){$(id).value=v;$(id==='hue'?'hueValue':id==='saturation'?'satValue':id==='brightness'?'brightValue':'alphaValue').textContent=Math.round(v)+label}$('colorRule').textContent=rule($('colorTarget').value,[$('colorProperty').value+': '+value+';'])}
function parseColor(text){let z=text.trim().replace(/^#/,'');if(!/^(?:[0-9a-f]{6}|[0-9a-f]{8})$/i.test(z))return false;const [r,g,b]=[0,2,4].map(i=>parseInt(z.slice(i,i+2),16)/255),max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;hue=d===0?0:max===r?60*((g-b)/d%6):max===g?60*((b-r)/d+2):60*((r-g)/d+4);if(hue<0)hue+=360;sat=max===0?0:d/max*100;bright=max*100;opacity=z.length===8?parseInt(z.slice(6),16)/255*100:100;refreshColor();return true}
for(const [id,fn]of [['hue',v=>hue=v],['saturation',v=>sat=v],['brightness',v=>bright=v],['alpha',v=>opacity=v]])$(id).oninput=()=>{fn(+$(id).value);refreshColor()};$('nativeColor').oninput=()=>parseColor($('nativeColor').value);$('hexColor').oninput=()=>{if(!parseColor($('hexColor').value)){$('hexColor').setAttribute('aria-invalid','true');$('colorStatus').textContent='Completá el color, por ejemplo #5C6AC4.'}};for(const id of ['colorTarget','colorProperty'])$(id).onchange=refreshColor;
const palette=[['Azul','#2563EB'],['Celeste','#38BDF8'],['Verde','#22C55E'],['Violeta','#8B5CF6'],['Rosa','#EC4899'],['Naranja','#F97316'],['Rojo','#EF4444'],['Gris','#334155']];$('colorPalette').innerHTML=palette.map(([name,c])=>`<button class="secondary" data-palette="${c}" aria-label="${name} ${c}"><span class="color-dot" style="background:${c}" aria-hidden="true"></span>${name}</button>`).join('');document.querySelectorAll('[data-palette]').forEach(b=>b.onclick=()=>parseColor(b.dataset.palette));$('applyColor').onclick=()=>{if($('hexColor').getAttribute('aria-invalid')){$('hexColor').focus();return}applyRule($('colorTarget').value,[$('colorProperty').value+': '+hex()+';'],'colorStatus','color '+$('colorProperty').value)};parseColor('#5C6AC4');
const fonts=[['Arial','Arial, sans-serif'],['Verdana','Verdana, sans-serif'],['Georgia','Georgia, serif'],['Times New Roman','"Times New Roman", serif'],['Trebuchet MS','"Trebuchet MS", sans-serif'],['Courier New','"Courier New", monospace']];let fontIndex=0;
function fontRule(){$('fontRule').textContent=rule($('fontTarget').value,['font-family: '+fonts[fontIndex][1]+';'])}
$('fonts').innerHTML=fonts.map(([name,value],i)=>`<button class="secondary" data-font="${i}" style="font-family:${esc(value)}" aria-pressed="${i===0}">${name}</button>`).join('');document.querySelectorAll('[data-font]').forEach(b=>b.onclick=()=>{fontIndex=+b.dataset.font;document.querySelectorAll('[data-font]').forEach(x=>x.setAttribute('aria-pressed',x===b));fontRule()});$('fontTarget').onchange=fontRule;$('applyFont').onclick=()=>applyRule($('fontTarget').value,['font-family: '+fonts[fontIndex][1]+';'],'fontStatus','fuente');fontRule();
function formatDeclarations(){return ['font-weight: '+($('bold').checked?'bold':'normal')+';','font-style: '+($('italic').checked?'italic':'normal')+';','text-decoration: '+($('underline').checked?'underline':'none')+';']}
function formatRule(){$('formatRule').textContent=rule($('formatTarget').value,formatDeclarations())}
for(const id of ['formatTarget','bold','italic','underline'])$(id).onchange=formatRule;$('applyFormat').onclick=()=>applyRule($('formatTarget').value,formatDeclarations(),'formatStatus','formato');formatRule();
const HTMLBLOCKS=[
['h1','Título principal','Presenta el título de la página.','En el contenido del body.','<h1>Mi título</h1>'],
['h2','Subtítulo','Introduce una sección.','En el contenido del body.','<h2>Otra sección</h2>'],
['p','Párrafo','Agrega un bloque de texto.','En el contenido del body.','<p>Un texto sobre mí.</p>'],
['br','Salto de línea','Pasa a la línea siguiente.','Dentro de un texto. El ejemplo incluye un párrafo.','<p>Primera línea<br>Segunda línea</p>'],
['ul','Lista sin orden','Crea una lista con viñetas.','En body; los li van dentro de la lista.','<ul>\n    <li>Primer elemento</li>\n    <li>Segundo elemento</li>\n</ul>'],
['ol','Lista ordenada','Crea una lista numerada.','En body; los li van dentro de la lista.','<ol>\n    <li>Primer elemento</li>\n    <li>Segundo elemento</li>\n</ol>'],
['li','Elemento de lista','Agrega un elemento a una lista.','Dentro de ul u ol. Se insertará en la lista existente.','<li>Mi nuevo interés</li>'],
['strong','Texto importante','Marca una parte importante del texto.','Dentro de un párrafo; el ejemplo incluye ese párrafo.','<p>Esta idea es <strong>importante</strong>.</p>'],
['div','Agrupación','Agrupa contenido.','Dentro del body.','<div>\n    <p>Un espacio para mis ideas.</p>\n</div>'],
['button','Botón','Muestra un botón.','Dentro del body. Este ejemplo no agrega acciones.','<button type="button">Mi botón</button>'],
['a','Enlace','Representa un enlace.','Dentro de un texto. En esta vista segura no se navega a otros sitios.','<p><a href="https://example.com">Un sitio para visitar</a></p>'],
['img','Imagen','Muestra una imagen y su descripción alternativa.','Dentro del body. Usá Agregar una imagen para cargar el archivo.','<img src="imagen.png" alt="Descripción de la imagen" width="320">']];
const CSSBLOCKS=[['color','Color del texto','color: blue;'],['background-color','Color de fondo','background-color: lightblue;'],['font-family','Tipo de letra','font-family: Arial, sans-serif;'],['font-size','Tamaño de texto','font-size: 32px;'],['font-weight','Grosor de texto','font-weight: bold;'],['font-style','Texto en cursiva','font-style: italic;'],['text-decoration','Subrayado','text-decoration: underline;'],['text-align','Alineación del texto','text-align: center;'],['margin','Espacio exterior','margin: 16px;'],['padding','Espacio interior','padding: 10px;'],['border','Borde del elemento','border: 1px solid blue;'],['border-radius','Esquinas redondeadas','border-radius: 8px;']];
let bank='html',blockIndex=0,blockSelector='h1';
function showBank(){const list=bank==='html'?HTMLBLOCKS:CSSBLOCKS;$('htmlBank').setAttribute('aria-pressed',bank==='html');$('cssBank').setAttribute('aria-pressed',bank==='css');$('blockList').innerHTML=list.map((b,i)=>`<button class="secondary" data-block="${i}" aria-pressed="${i===blockIndex}">${esc(bank==='html'?'<'+b[0]+'>':b[0])}</button>`).join('');const b=list[blockIndex];$('blockInfo').innerHTML=bank==='html'?`<h3>${esc(b[1])} <code>&lt;${b[0]}&gt;</code></h3><p>${esc(b[2])}</p><p><strong>Dónde:</strong> ${esc(b[3])}</p><pre>${esc(b[4])}</pre><button id="insertBlock">Insertar HTML</button>`:`<h3>${esc(b[0])}</h3><p>Modifica: ${esc(b[1].toLowerCase())}.</p><p>Se escribe dentro de las llaves del elemento que elegís.</p><label for="blockSelector">¿A qué elemento?</label><select id="blockSelector">${['body','h1','h2','p','ul','li','div','button','img'].map(v=>`<option ${v===blockSelector?'selected':''}>${v}</option>`).join('')}</select><pre id="blockRule">${esc(rule(blockSelector,[b[2]]))}</pre><button id="insertBlock">Insertar regla CSS</button>`;document.querySelectorAll('[data-block]').forEach(x=>x.onclick=()=>{blockIndex=+x.dataset.block;showBank();document.querySelector(`[data-block="${blockIndex}"]`)?.focus()});if($('blockSelector'))$('blockSelector').onchange=()=>{blockSelector=$('blockSelector').value;$('blockRule').textContent=rule(blockSelector,[b[2]])};$('insertBlock').onclick=()=>bank==='html'?updateCode('html',htmlInsertion(b[4],b[0]),'blockStatus'):applyRule(blockSelector,[b[2]],'blockStatus','bloque '+b[0])}
$('htmlBank').onclick=()=>{bank='html';blockIndex=0;showBank()};$('cssBank').onclick=()=>{bank='css';blockIndex=0;showBank()};showBank();
let pendingImage=null,imageTicket=0;
function imageMarkup(){return pendingImage?`<img src="${pendingImage.name}" alt="${esc($('imageAlt').value.trim())}" width="320">`:''}
$('imageAlt').oninput=()=>{if(pendingImage)$('imageCode').textContent=imageMarkup()};
$('imageFile').onchange=async()=>{const ticket=++imageTicket;pendingImage=null;$('insertImage').disabled=true;$('imageCode').textContent='Elegí una imagen para ver el código.';const file=$('imageFile').files[0];if(!file)return;const allowed={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif'};if(!allowed[file.type]){$('imageStatus').textContent='Elegí una imagen JPG, PNG, WEBP o GIF.';return}if(file.size>1024*1024){$('imageStatus').textContent='Esta imagen supera 1 MB. Elegí una más pequeña para que la página cargue con fluidez.';return}try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});await new Promise((resolve,reject)=>{const im=new Image();im.onload=resolve;im.onerror=reject;im.src=data});if(ticket!==imageTicket)return;pendingImage={name:'imagen-'+Date.now()+'.'+allowed[file.type],data};$('imageCode').textContent=imageMarkup();$('insertImage').disabled=false;$('imageStatus').textContent='Imagen preparada. Describila y pulsá Insertar imagen para verla en tu HTML.'}catch(e){if(ticket===imageTicket)$('imageStatus').textContent='No pudimos leer esta imagen. Probá con otro archivo.'}};
$('insertImage').onclick=()=>{if(!pendingImage)return;if(!$('imageAlt').value.trim()){$('imageStatus').textContent='Escribí una descripción breve de la imagen antes de insertarla.';$('imageAlt').focus();return}const html=htmlInsertion(imageMarkup());if(html.length>$('htmlCode').maxLength){$('imageStatus').textContent='El editor HTML está lleno. Quitá algo de código antes de insertar.';return}state.images[pendingImage.name]=pendingImage.data;updateCode('html',html,'imageStatus');const omitted=snapshot().imagesOmitted;$('imageStatus').textContent=omitted?'Imagen insertada en HTML. Para conservar esta imagen al salir, descargá el proyecto: supera el espacio disponible de guardado.':'Imagen insertada en HTML · observá el resultado y editá el código si querés.';$('insertImage').disabled=true;pendingImage=null;};
